server:
  port: 8081

spring:
  application:
    name: passenger-microservice

  data:
    mongodb:
      uri: ${SPRING_MONGODB_URL:mongodb://localhost:27017/passengers_db}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: passenger-ratings

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/cab-agg}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka: ERROR

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.request]": true
  prometheus:
    metrics:
      export:
        enabled: true